/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ccnliteinterface_CCNLiteInterface */

#ifndef _Included_ccnliteinterface_CCNLiteInterface
#define _Included_ccnliteinterface_CCNLiteInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ccnliteinterface_CCNLiteInterface
 * Method:    mkBinaryInterest
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ccnliteinterface_CCNLiteInterface_mkBinaryInterest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ccnliteinterface_CCNLiteInterface
 * Method:    mkBinaryContent
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ccnliteinterface_CCNLiteInterface_mkBinaryContent
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     ccnliteinterface_CCNLiteInterface
 * Method:    mkAddToCacheInterest
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ccnliteinterface_CCNLiteInterface_mkAddToCacheInterest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ccnliteinterface_CCNLiteInterface
 * Method:    ccnbToXml
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ccnliteinterface_CCNLiteInterface_ccnbToXml
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
