/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ccnliteinterface_jni_CCNLiteInterfaceCCNbJni */

#ifndef _Included_ccnliteinterface_jni_CCNLiteInterfaceCCNbJni
#define _Included_ccnliteinterface_jni_CCNLiteInterfaceCCNbJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ccnliteinterface_jni_CCNLiteInterfaceCCNbJni
 * Method:    mkBinaryInterest
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ccnliteinterface_jni_CCNLiteInterfaceCCNbJni_mkBinaryInterest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ccnliteinterface_jni_CCNLiteInterfaceCCNbJni
 * Method:    mkBinaryContent
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ccnliteinterface_jni_CCNLiteInterface_mkBinaryContent
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     ccnliteinterface_jni_CCNLiteInterfaceCCNbJni
 * Method:    mkAddToCacheInterest
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ccnliteinterface_jni_CCNLiteInterface_mkAddToCacheInterest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ccnliteinterface_jni_CCNLiteInterfaceCCNbJni
 * Method:    ccnbToXml
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ccnliteinterface_jni_CCNLiteInterfaceCCNbJni_ccnbToXml
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
