//
// Generated file, do not edit! Created by opp_msgc 4.5 from CcnPacket.msg.
//

#ifndef _CCNPACKET_M_H_
#define _CCNPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "INETDefs.h"
#include "ByteArrayMessage.h"
// }}



/**
 * Enum generated from <tt>CcnPacket.msg</tt> by opp_msgc.
 * <pre>
 * enum CcnPayloadType {
 *     MSG_TYPE_INTEREST = 0;
 *     MSG_TYPE_CONTENT = 1;
 *     MSG_TYPE_DATA = 1;
 * };
 * </pre>
 */
enum CcnPayloadType {
    MSG_TYPE_INTEREST = 0,
    MSG_TYPE_CONTENT = 1,
    MSG_TYPE_DATA = 1
};

/**
 * Enum generated from <tt>CcnPacket.msg</tt> by opp_msgc.
 * <pre>
 * enum CcnSuiteType {
 *     SUITE_CCNx0 = 1;
 *     SUITE_CCNx1 = 2;
 *     SUITE_NDNx0 = 3;
 * };
 * </pre>
 */
enum CcnSuiteType {
    SUITE_CCNx0 = 1,
    SUITE_CCNx1 = 2,
    SUITE_NDNx0 = 3
};

/**
 * Class generated from <tt>CcnPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet CcnPacket extends ByteArrayMessage {
 *     byteLength = 6;		
 *     					
 *     					
 *     					
 *     					
 *     
 *     long cacheId;
 *     char suiteType @enum(CcnSuiteType);
 *     char msgPayloadType @enum(CcnPayloadType);
 * }
 * </pre>
 */
class CcnPacket : public ::ByteArrayMessage
{
  protected:
    long cacheId_var;
    char suiteType_var;
    char msgPayloadType_var;

  private:
    void copy(const CcnPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CcnPacket&);

  public:
    CcnPacket(const char *name=NULL, int kind=0);
    CcnPacket(const CcnPacket& other);
    virtual ~CcnPacket();
    CcnPacket& operator=(const CcnPacket& other);
    virtual CcnPacket *dup() const {return new CcnPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual long getCacheId() const;
    virtual void setCacheId(long cacheId);
    virtual char getSuiteType() const;
    virtual void setSuiteType(char suiteType);
    virtual char getMsgPayloadType() const;
    virtual void setMsgPayloadType(char msgPayloadType);
};

inline void doPacking(cCommBuffer *b, CcnPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CcnPacket& obj) {obj.parsimUnpack(b);}


#endif // _CCNPACKET_M_H_
