/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CCNLiteInterface */

#ifndef _Included_CCNLiteInterface
#define _Included_CCNLiteInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CCNLiteInterface
 * Method:    mkBinaryInterest
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CCNLiteInterface_mkBinaryInterest
  (JNIEnv *, jobject, jstring);

/*
 * Class:     CCNLiteInterface
 * Method:    mkBinaryContent
 * Signature: (Ljava/lang/String;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CCNLiteInterface_mkBinaryContent
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     CCNLiteInterface
 * Method:    ccnbToXml
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CCNLiteInterface_ccnbToXml
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
